# Site settings
title: "nicolasdamians"
bye_message: ""
baseurl: "/"
url: "https://nicolasdamians.github.io/"

# Header settings
nick: "nicolasdamians"
mail:
    domain: "nicods"
    ext: "com"
source_code:
    server: "github.com"
    nick: "nicolasdamians"
fingerprint_key: "894F E13F C25A 47FF 1AE4  F643 452A D28A A3D2 C6B6"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
